version: '3'
services:
  subconverter:
    build:
      context: .
      dockerfile: ./scripts/Dockerfile
      tags:
        - techhexad/subconverter:latest

    # image: asdlokj1qpi23/subconverter:latest
    container_name: subconverter
    ports:
      - "25500:25500"
    restart: always
    # volumes:
    #   - ./base/subconverter:/usr/bin/subconverter